[project]
name = "glorys_northeast"
version = "0.1.0"
description = "Add a short description here"
authors = ["adamkemberling <adamkemberling@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
xarray = ">=2025.3.1,<2025.4"
python = ">=3.13.3,<3.14"
copernicusmarine = { version = ">=2.0.1,<2.1", channel = "conda-forge" }
numpy = ">=2.2.5,<2.3"
matplotlib = ">=3.10.1,<3.11"
shapely = ">=2.1.0,<2.2"
geopandas = ">=1.0.1,<1.1"
ipykernel = ">=6.29.5,<6.30"
pip = ">=25.0.1,<25.1"
regionmask = ">=0.13.0,<0.14"
